<?php

namespace Webeak\Bundle\FileBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;
use Webeak\Bundle\EssentialBundle\Exception\UsageException;
use Webeak\Bundle\FileBundle\Bridge\Doctrine\Orm\Entity\File;
use Webeak\Bundle\FileBundle\Bridge\Doctrine\Orm\Entity\FileEntityInterface;
use Webeak\Bundle\FileBundle\FileSystem\FileSystemConfigValidator;

/**
 * This is the class that validates and merges configuration from your app/config files.
 *
 * To learn more see {@link http://symfony.com/doc/current/cookbook/bundles/configuration.html}
 */
class Configuration implements ConfigurationInterface
{
    /**
     * {@inheritdoc}
     */
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder('wb_file');
        $treeBuilder->getRootNode()
            ->addDefaultsIfNotSet()
            ->children()
                ->integerNode('temp_files_lifetime')
                    ->info('Lifespan of temp files. They will be cleaned up by the command "wb:file:clear".')
                    ->min(60) // 1 minute
                    ->defaultValue(60 * 60 * 2) // 2 hours
                ->end()
                ->scalarNode('not_found_image_path')
                    ->info('Path to the image to show when an inexisting image is requested. If null the default internal image will be used.')
                    ->defaultNull()
                ->end()
                ->scalarNode('access_denied_image_path')
                    ->info('Path to the image to show when a user try to access an image he doesn\'t have access to. If null the default internal image will be used.')
                    ->defaultNull()
                ->end()
                ->arrayNode('constraints_aliases')
                    ->info('Define more user-friendly names for constraints FQCN.')
                    ->prototype('scalar')
                        ->beforeNormalization()
                            ->ifString()
                            ->then(function($v) { return str_replace('/', '\\', $v); })
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('configuration_presets')
                    ->info('Define a preset configuration. You can then use the preset name to build a full Configuration object easily. Used by temporarily uploads for example.')
                    ->prototype('array')
                        ->children()
                            ->arrayNode('constraints')
                                ->prototype('array')
                                    ->prototype('variable')
                                    ->end()
                                ->end()
                            ->end()
                            ->arrayNode('processors')
                                ->prototype('array')
                                    ->prototype('variable')
                                    ->end()
                                ->end()
                            ->end()
                            ->arrayNode('requiredRoles')
                                ->addDefaultsIfNotSet()
                            ->end()
                            ->arrayNode('whiteListExclusive')
                                ->addDefaultsIfNotSet()
                            ->end()
                            ->arrayNode('whiteListCumulative')
                                ->addDefaultsIfNotSet()
                            ->end()
                            ->arrayNode('blackList')
                                ->addDefaultsIfNotSet()
                            ->end()
                            ->scalarNode('public')
                                ->defaultFalse()
                            ->end()
                            ->scalarNode('autoConfirm')
                                ->defaultFalse()
                            ->end()
                            ->arrayNode('extra')
                                ->prototype('variable')
                                ->end()
                            ->end()
                            ->arrayNode('publicExtra')
                                ->prototype('variable')
                                ->end()
                            ->end()
                            ->scalarNode('filesystem')
                                ->defaultNull()
                            ->end()
                            ->scalarNode('storage')
                                ->defaultNull()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->scalarNode('default_storage')
                    ->info('Type of storage to use to store files\' metadata.')
                    ->defaultValue('filesystem')
                ->end()
                ->arrayNode('storages')
                    ->info('List of available storages.')
                    ->useAttributeAsKey('name')
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('type')
                                ->isRequired()
                                ->info('Type of the storage, e.g., doctrine, filesystem, etc.')
                            ->end()
                            ->scalarNode('entity_class')
                                ->info('FQCN of the entity to use to save files. The entity must implement the "FileEntityInterface" or intherit from "AbstractFile".')
                                ->defaultValue(File::class)
                                ->beforeNormalization()
                                    ->ifString()
                                    ->then(function($v) {
                                        $fqcn = str_replace('/', '\\', $v);
                                        $refl = new \ReflectionClass($fqcn);
                                        if (!$refl->implementsInterface(FileEntityInterface::class)) {
                                            throw new UsageException(sprintf('Class "%s" must implement the "FileEntityInterface" interface.', $fqcn));
                                        }
                                        return $fqcn;
                                    })
                                ->end()
                            ->end()
                            ->scalarNode('entity_id_attr')
                                ->info('Name of the attribute holding the file identifier in the database entity.')
                                ->defaultValue('ref')
                            ->end()
                            ->scalarNode('entity_manager')
                                ->info('Name of the entity manager to use to persist the entities.')
                                ->defaultNull()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->scalarNode('default_filesystem')
                    ->info('The default filesystem to use.')
                    ->defaultValue('local')
                ->end()
                ->arrayNode('filesystems')
                    ->info('List of available filesystems.')
                    ->useAttributeAsKey('name')
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('type')
                                ->isRequired()
                                ->info('Type of the filesystem, e.g., local, aws_s3, proxy, etc.')
                            ->end()
                            ->scalarNode('save_path')
                                ->info('Root directory where local files should be written (local, root dir for ftp / sftp).')
                                ->defaultNull()
                            ->end()
                            ->scalarNode('public_base_url')
                                ->info('Optional base url to use to directly access the files (ignoring the proxy) (applicable to all filesystems).')
                                ->defaultNull()
                            ->end()
                            ->scalarNode('region')
                                ->info('Region of the S3 bucket (aws_s3).')
                                ->defaultNull()
                            ->end()
                            ->scalarNode('bucket')
                                ->info('Name of the S3 bucket (aws_s3).')
                                ->defaultNull()
                            ->end()
                            ->scalarNode('baseUrl')
                                ->info('Base url for http calls to the proxy (proxy).')
                                ->defaultNull()
                            ->end()
                                ->scalarNode('key')
                                ->info('Authentication key (S3).')
                            ->defaultNull()
                            ->end()
                                ->scalarNode('secret')
                                ->info('Authentication secret (S3).')
                            ->defaultNull()
                            ->end()
                            ->scalarNode('host')
                                ->info('Host to which to connect (ftp / sftp).')
                                ->defaultNull()
                            ->end()
                            ->scalarNode('username')
                                ->info('Authentication username (ftp / sftp).')
                                ->defaultNull()
                            ->end()
                            ->scalarNode('password')
                                ->info('Authentication password (ftp / sftp).')
                                ->defaultNull()
                            ->end()
                            ->scalarNode('port')
                                ->info('Port number (ftp / sftp).')
                                ->defaultValue(21)
                            ->end()
                            ->scalarNode('passive')
                                ->info('Passive mode (ftp).')
                                ->defaultTrue()
                            ->end()
                            ->scalarNode('ssl')
                                ->info('Enable SSL connection (ftp).')
                                ->defaultFalse()
                            ->end()
                            ->scalarNode('timeout')
                                ->info('Connection timeout (ftp / sftp).')
                                ->defaultValue(30)
                            ->end()
                            ->scalarNode('private_key')
                                ->info('Private key file (sftp).')
                                ->defaultNull()
                            ->end()
                            ->scalarNode('passphrase')
                                ->info('Passphrase for the private key (sftp).')
                                ->defaultNull()
                            ->end()
                            ->scalarNode('visibility')
                                ->info('Default file visibility (public/private).')
                                ->defaultValue('private')
                            ->end()
                            ->scalarNode('connection_string')
                                ->info('Azure Storage connection string.')
                                ->defaultNull()
                            ->end()
                                ->scalarNode('container')
                                ->info('Azure Blob container name.')
                            ->defaultNull()
                            ->end()
                            ->scalarNode('prefix')
                                ->info('Optional prefix inside the container.')
                                ->defaultNull()
                            ->end()
                            ->arrayNode('permissions')
                                ->info('Permissions for files and directories.')
                                ->addDefaultsIfNotSet()
                                ->children()
                                    ->arrayNode('file')
                                        ->addDefaultsIfNotSet()
                                        ->children()
                                            ->integerNode('public')
                                                ->info('Permissions for public files.')
                                                ->defaultValue(0644)
                                                ->beforeNormalization()
                                                    ->always(function ($v) { return is_numeric($v) ? intval(octdec((string) $v)) : $v; }) // Ensure octal
                                                ->end()
                                            ->end()
                                            ->integerNode('private')
                                                ->info('Permissions for private files.')
                                                ->defaultValue(0600)
                                                ->beforeNormalization()
                                                    ->always(function ($v) { return is_numeric($v) ? intval(octdec((string) $v)) : $v; }) // Ensure octal
                                                ->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                    ->arrayNode('dir')
                                        ->addDefaultsIfNotSet()
                                        ->children()
                                            ->integerNode('public')
                                                ->info('Permissions for public directories.')
                                                ->defaultValue(0755)
                                                ->beforeNormalization()
                                                    ->always(function ($v) { return is_numeric($v) ? intval(octdec((string) $v)) : $v; }) // Ensure octal
                                                ->end()
                                            ->end()
                                            ->integerNode('private')
                                                ->info('Permissions for private directories.')
                                                ->defaultValue(0700)
                                                ->beforeNormalization()
                                                    ->always(function ($v) { return is_numeric($v) ? intval(octdec((string) $v)) : $v; }) // Ensure octal
                                                ->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                        ->validate()
                            ->ifTrue(function ($v) {
                                return !FilesystemConfigValidator::validate($v);
                            })
                            ->thenInvalid('Invalid filesystem configuration.')
                        ->end()
                    ->end()
                ->end()
            ->end();
        return $treeBuilder;
    }
}
