doctrine:
    orm:
        mappings:
            WebeakFileBundle:
                type: annotation
                dir: "Bridge/Doctrine/Orm/Entity"
                alias: FileBundle
                prefix: "Webeak\\Bundle\\FileBundle\\Bridge\\Doctrine\\Orm\\Entity"
                is_bundle: true
