doctrine:
    orm:
        mappings:
            WebeakFileBundle:
                is_bundle: true
                type: attribute
                dir: 'Bridge/Doctrine/Orm/Entity'
                alias: FileBundle
                prefix: Webeak\Bundle\FileBundle\Bridge\Doctrine\Orm\Entity
