services:
    #
    # Defines controllers as services and set autowire and autoconfigure because they are at false by default.
    #
    Webeak\Bundle\FileBundle\Controller\:
        autowire: true
        autoconfigure: true
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    #
    # Declare commands.
    #
    Webeak\Bundle\FileBundle\Command\:
        autowire: true
        autoconfigure: true
        resource: '../../Command'
        tags: ['console.command']

    #
    # Main services
    #
    Webeak\Bundle\FileBundle\FileManager:
        public: true
        arguments:
            - '@service_container'
            - '@validator'
            - '@Webeak\Bundle\DoctrineExtensionsBundle\Utils\UniqueIdGenerator'
            - '@Webeak\Bundle\FileBundle\FileIdentifierManager'
            - '@Webeak\Bundle\EssentialBundle\RandomTaskFactory'
            - '@Webeak\Bundle\FileBundle\Storage\StorageCollection'
            - '%wb.file.temp_files_lifetime%'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.terminate', method: onKernelTerminate }

    Webeak\Bundle\FileBundle\ConfigurationBuilder:
        public: true
        shared: false
        arguments:
            - '@service_container'
            - '%wb.file.configuration_presets%'
            - '%wb.file.constraints_aliases%'
            - '%wb.file.processors_aliases%'

    Webeak\Bundle\FileBundle\ManagedFile:
        public: true
        shared: false
        arguments:
            - '@router'
            - '@Webeak\Bundle\FileBundle\FileSystem\FileSystemCollection'
            - '@Webeak\Bundle\FileBundle\FileIdentifierManager'
            - '%wb.file.default_filesystem%'
            - '%wb.file.default_storage%'
            - '%wb.file.filesystems_public_paths%'

    Webeak\Bundle\FileBundle\FileIdentifierManager:
        public: true
        shared: false
        arguments:
            - '@Webeak\Bundle\EssentialBundle\SharedStorage\SharedStorageInterface'
            - '@Webeak\Bundle\FileBundle\Storage\StorageCollection'

    #
    # Adapters
    #
    Webeak\Bundle\FileBundle\Adapter\FileAdapter:
        tags:
            - { name: wb.file.file_manager_adapter }

    Webeak\Bundle\FileBundle\Adapter\UploadedFileAdapter:
        tags:
            - { name: wb.file.file_manager_adapter }

    Webeak\Bundle\FileBundle\Adapter\HttpPathAdapter:
        arguments:
            - '@http_client'
        tags:
            - { name: wb.file.file_manager_adapter }

    Webeak\Bundle\FileBundle\Adapter\LocalPathAdapter:
        tags:
            - { name: wb.file.file_manager_adapter }

    #
    # Processors
    #
    Webeak\Bundle\FileBundle\Processor\CreateVersionProcessor:
        tags:
            - { name: wb.file.file_manager_processor, alias: createVersion }

    Webeak\Bundle\FileBundle\Processor\ResizeProcessor:
        arguments: ['@image.handling']
        tags:
            - { name: wb.file.file_manager_processor, alias: resize }

    #
    # Storage
    #
    Webeak\Bundle\FileBundle\Storage\StorageCollection: ~

    #
    # FileSystem
    #
    Webeak\Bundle\FileBundle\FileSystem\FileSystemCollection: ~

    #
    # Normalizer
    #
    Webeak\Bundle\FileBundle\Serializer\PublicFileNormalizer:
        public: false
        arguments:
            - '@Webeak\Bundle\FileBundle\FileManager'
            - '%kernel.environment%'
        tags: [ { name: serializer.normalizer } ]

    Webeak\Bundle\FileBundle\Serializer\PublicFileCollectionNormalizer:
        public: false
        arguments:
            - '@Webeak\Bundle\FileBundle\FileManager'
            - '%kernel.environment%'
        tags: [ { name: serializer.normalizer } ]

    #
    # Doctrine
    #
    Webeak\Bundle\FileBundle\Bridge\Doctrine\Orm\EventListener\EntityListener:
        public: false
        arguments: ['@Webeak\Bundle\FileBundle\FileManager']
        tags:
            - { name: wb.doctrine_extensions.listener, event: postLoad, method: postLoad, priority: 1 }
            - { name: wb.doctrine_extensions.listener, event: onFlush, method: onFlush, priority: 1000 }

    #
    # Commands
    #
    Webeak\Bundle\FileBundle\Command\ClearExpiredFilesCommand:
        arguments:
            - '@Webeak\Bundle\FileBundle\FileManager'
        tags:
            - { name: 'console.command', command: 'wb:file:clear-expired' }

    Webeak\Bundle\FileBundle\Command\ClearTempFilesCommand:
        tags:
            - { name: 'console.command', command: 'wb:file:clear' }
