services:
    #
    # Defines controllers as services and set autowire and autoconfigure because they are at false by default.
    #
    Webeak\Bundle\FileBundle\Controller\:
        autowire: true
        autoconfigure: true
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    #
    # Declare commands.
    #
    Webeak\Bundle\FileBundle\Command\:
        autowire: true
        autoconfigure: true
        resource: '../../Command'
        tags: ['console.command']

    #
    # Main services
    #
    Webeak\Bundle\FileBundle\FileManager:
        public: true
        arguments:
            - '@service_container'
            - '@validator'
            - '@Webeak\Bundle\ErrorTrackerBundle\ErrorTrackerInterface'
            - '@Webeak\Bundle\EssentialBundle\UniqueIdGenerator'
            - '@Webeak\Bundle\FileBundle\FileSystem'
            - '@Webeak\Bundle\EssentialBundle\RandomTaskFactory'
            - '%wb_file.storage_type%'
            - '%wb_file.temp_files_lifetime%'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.terminate', method: onKernelTerminate }

    Webeak\Bundle\FileBundle\ConfigurationBuilder:
        public: true
        shared: false
        arguments:
            - '@service_container'
            - '@Webeak\Bundle\ErrorTrackerBundle\ErrorTrackerInterface'
            - '%wb_file.configuration_presets%'
            - '%wb_file.constraints_aliases%'
            - '%wb_file.processors_aliases%'

    Webeak\Bundle\FileBundle\FileSystem:
        arguments:
            - '@Webeak\Bundle\ErrorTrackerBundle\ErrorTrackerInterface'
            - '@filesystem'
            - '%wb_file.save_path%'
            - '%wb_file.public_save_path%'

    Webeak\Bundle\FileBundle\ManagedFile:
        public: true
        shared: false
        arguments:
            - '@Webeak\Bundle\ErrorTrackerBundle\ErrorTrackerInterface'
            - '@Webeak\Bundle\FileBundle\FileSystem'
            - '@router'
            - '%wb_file.http_root%'
            - '%kernel.project_dir%'

    #
    # Adapters
    #
    Webeak\Bundle\FileBundle\Adapter\FileAdapter:
        tags:
            - { name: wb.file.file_manager_adapter }

    Webeak\Bundle\FileBundle\Adapter\UploadedFileAdapter:
        arguments:
            - '@Webeak\Bundle\ErrorTrackerBundle\ErrorTrackerInterface'
            - '@Webeak\Bundle\FileBundle\FileSystem'
        tags:
            - { name: wb.file.file_manager_adapter }

    Webeak\Bundle\FileBundle\Adapter\HttpPathAdapter:
        arguments:
            - '@Webeak\Bundle\FileBundle\FileSystem'
            - '@Webeak\Bundle\ErrorTrackerBundle\ErrorTrackerInterface'
        tags:
            - { name: wb.file.file_manager_adapter }

    Webeak\Bundle\FileBundle\Adapter\LocalPathAdapter:
        arguments:
            - '@Webeak\Bundle\FileBundle\FileSystem'
            - '@Webeak\Bundle\ErrorTrackerBundle\ErrorTrackerInterface'
        tags:
            - { name: wb.file.file_manager_adapter }

    #
    # Processors
    #
    Webeak\Bundle\FileBundle\Processor\CreateVersionProcessor:
        arguments: ['@Webeak\Bundle\FileBundle\FileSystem']
        tags:
            - { name: wb.file.file_manager_processor, alias: createVersion }

    Webeak\Bundle\FileBundle\Processor\ResizeProcessor:
        arguments: ['@image.handling']
        tags:
            - { name: wb.file.file_manager_processor, alias: resize }

    #
    # Storage
    #
    Webeak\Bundle\FileBundle\Storage\FileSystemStorage:
        arguments:
            - '@service_container'
            - '@kernel'
            - '@Webeak\Bundle\ErrorTrackerBundle\ErrorTrackerInterface'
            - '@Webeak\Bundle\FileBundle\FileSystem'
        calls:
            - [setSharedStorage, ['@?Webeak\Bundle\SharedStorageBundle\SharedStorageInterface']]
        tags:
            - { name: wb_file.file_manager_storage, alias: filesystem }

    Webeak\Bundle\FileBundle\Storage\DoctrineStorage:
        arguments:
            - '@service_container'
            - '@doctrine'
            - '@Webeak\Bundle\ErrorTrackerBundle\ErrorTrackerInterface'
            - '@Webeak\Bundle\FileBundle\FileSystem'
            - '%wb_file.doctrine_storage%'
        tags:
            - { name: wb_file.file_manager_storage, alias: doctrine }

    #
    # Normalizer
    #
    Webeak\Bundle\FileBundle\Serializer\PublicFileNormalizer:
        public: false
        arguments:
            - '@Webeak\Bundle\FileBundle\FileManager'
            - '@Webeak\Bundle\ErrorTrackerBundle\ErrorTrackerInterface'
            - '%kernel.environment%'
        tags: [ { name: serializer.normalizer } ]

    Webeak\Bundle\FileBundle\Serializer\PublicFileCollectionNormalizer:
        public: false
        arguments:
            - '@Webeak\Bundle\FileBundle\FileManager'
            - '@Webeak\Bundle\ErrorTrackerBundle\ErrorTrackerInterface'
            - '%kernel.environment%'
        tags: [ { name: serializer.normalizer } ]

    #
    # Doctrine
    #
    Webeak\Bundle\FileBundle\Bridge\Doctrine\Orm\EventListener\EntityListener:
        public: false
        arguments: ['@Webeak\Bundle\FileBundle\FileManager', '@Webeak\Bundle\ErrorTrackerBundle\ErrorTrackerInterface']
        tags:
            - { name: wb_essentials.doctrine.listener, event: postLoad, method: postLoad, priority: 1 }
            - { name: wb_essentials.doctrine.listener, event: onFlush, method: onFlush, priority: 1000 }
