services:
    #
    # Defines controllers as services and set autowire and autoconfigure because they are at false by default.
    #
    Webeak\Bundle\FileBundle\Controller\:
        autowire: true
        autoconfigure: true
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    #
    # Declare commands.
    #
    Webeak\Bundle\FileBundle\Command\:
        autowire: true
        autoconfigure: true
        resource: '../../Command'
        tags: ['console.command']

    #
    # Main services
    #
    Webeak\Bundle\FileBundle\FileManager:
        public: true
        arguments:
            - '@service_container'
            - '@validator'
            - '@Webeak\Bundle\DoctrineExtensionsBundle\Utils\UniqueIdGenerator'
            - '@Webeak\Bundle\FileBundle\FileSystem\FileSystemInterface'
            - '@Webeak\Bundle\EssentialBundle\RandomTaskFactory'
            - '%wb.file.storage_type%'
            - '%wb.file.temp_files_lifetime%'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.terminate', method: onKernelTerminate }

    Webeak\Bundle\FileBundle\ConfigurationBuilder:
        public: true
        shared: false
        arguments:
            - '@service_container'
            - '%wb.file.configuration_presets%'
            - '%wb.file.constraints_aliases%'
            - '%wb.file.processors_aliases%'

    Webeak\Bundle\FileBundle\ManagedFile:
        public: true
        shared: false
        arguments:
            - '@request_stack'
            - '@Webeak\Bundle\FileBundle\FileSystem\FileSystemInterface'
            - '@router'
            - '%kernel.project_dir%'

    #
    # Adapters
    #
    Webeak\Bundle\FileBundle\Adapter\FileAdapter:
        tags:
            - { name: wb.file.file_manager_adapter }

    Webeak\Bundle\FileBundle\Adapter\UploadedFileAdapter:
        arguments:
            - '@Webeak\Bundle\FileBundle\FileSystem\FileSystemInterface'
        tags:
            - { name: wb.file.file_manager_adapter }

    Webeak\Bundle\FileBundle\Adapter\HttpPathAdapter:
        arguments:
            - '@Webeak\Bundle\FileBundle\FileSystem\FileSystemInterface'
        tags:
            - { name: wb.file.file_manager_adapter }

    Webeak\Bundle\FileBundle\Adapter\LocalPathAdapter:
        arguments:
            - '@Webeak\Bundle\FileBundle\FileSystem\FileSystemInterface'
        tags:
            - { name: wb.file.file_manager_adapter }

    #
    # Processors
    #
    Webeak\Bundle\FileBundle\Processor\CreateVersionProcessor:
        arguments: ['@Webeak\Bundle\FileBundle\FileSystem\FileSystemInterface']
        tags:
            - { name: wb.file.file_manager_processor, alias: createVersion }

    Webeak\Bundle\FileBundle\Processor\ResizeProcessor:
        arguments: ['@image.handling']
        tags:
            - { name: wb.file.file_manager_processor, alias: resize }

    #
    # Storage
    #
    Webeak\Bundle\FileBundle\Storage\FileSystemStorage:
        arguments:
            - '@service_container'
            - '@kernel'
            - '@Psr\Log\LoggerInterface'
            - '@Webeak\Bundle\FileBundle\FileSystem\FileSystemInterface'
        calls:
            - [setSharedStorage, ['@Webeak\Bundle\EssentialBundle\SharedStorage\SharedStorageInterface']]
        tags:
            - { name: wb.file.file_manager_storage, alias: filesystem }

    Webeak\Bundle\FileBundle\Storage\DoctrineStorage:
        arguments:
            - '@service_container'
            - '@doctrine'
            - '@Webeak\Bundle\FileBundle\FileSystem\FileSystemInterface'
            - '%wb.file.doctrine_storage%'
        tags:
            - { name: wb.file.file_manager_storage, alias: doctrine }

    #
    # FileSystem
    #
    Webeak\Bundle\FileBundle\FileSystem\FileSystemInterface: ~

    Webeak\Bundle\FileBundle\FileSystem\LocalFileSystem:
        public: true
        arguments:
            - '@filesystem'
            - '%wb.file.save_path%'
            - '%wb.file.public_save_path%'
        tags:
            - { name: wb.file.file_filesystem, alias: local }

    Webeak\Bundle\FileBundle\FileSystem\AwsS3FileSystem:
        public: true
        arguments:
            - '@filesystem'
            - '@Webeak\Bundle\FileBundle\Aws\S3Bucket'
            - '%wb.file.save_path%'
            - '%wb.file.public_save_path%'
        tags:
            - { name: wb.file.file_filesystem, alias: aws_s3 }

    #
    # Normalizer
    #
    Webeak\Bundle\FileBundle\Serializer\PublicFileNormalizer:
        public: false
        arguments:
            - '@Webeak\Bundle\FileBundle\FileManager'
            - '%kernel.environment%'
        tags: [ { name: serializer.normalizer } ]

    Webeak\Bundle\FileBundle\Serializer\PublicFileCollectionNormalizer:
        public: false
        arguments:
            - '@Webeak\Bundle\FileBundle\FileManager'
            - '%kernel.environment%'
        tags: [ { name: serializer.normalizer } ]

    #
    # Doctrine
    #
    Webeak\Bundle\FileBundle\Bridge\Doctrine\Orm\EventListener\EntityListener:
        public: false
        arguments: ['@Webeak\Bundle\FileBundle\FileManager']
        tags:
            - { name: wb.doctrine_extensions.listener, event: postLoad, method: postLoad, priority: 1 }
            - { name: wb.doctrine_extensions.listener, event: onFlush, method: onFlush, priority: 1000 }

    #
    # Commands
    #
    Webeak\Bundle\FileBundle\Command\ClearExpiredFilesCommand:
        arguments:
            - '@Webeak\Bundle\FileBundle\FileManager'
        tags:
            - { name: 'console.command', command: 'wb:file:clear-expired' }

    Webeak\Bundle\FileBundle\Command\ClearTempFilesCommand:
        arguments:
            - '@Webeak\Bundle\FileBundle\FileSystem\FileSystemInterface'
        tags:
            - { name: 'console.command', command: 'wb:file:clear' }

    #
    # AWS
    #
    Webeak\Bundle\FileBundle\Aws\S3Bucket:
        public: true
        arguments:
            - '%wb.file.aws_s3_storage%'
